name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: '3.7.0'   # Versión estable que incluye Dart 3.7.0
      FLUTTER_CHANNEL: stable
      BASE_HREF: "/SIGEDIN/"

    steps:
    - uses: actions/checkout@v3

    - name: Install Flutter (stable)
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: ${{ env.FLUTTER_CHANNEL }}

    - run: flutter config --enable-web
    - run: flutter pub get
    - run: flutter build web --release --base-href="${{ env.BASE_HREF }}"

    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web